export const TrainsObject = [
    {
        'id': '1',
        'nev': 'Mk48',
        'value': 'mk48',
        'gyartasiev': '1960-1961',
        'ittkozlekedik': '1961 óta',
        'eredetidb':'9 db',
        'jelenlegidb': '2 db',
        'megjegyzes': '	A 2000-es évekre négy darab ilyen mozdony maradt, melyeket modernizálás során 2020-től kezdve egy kivételével átépítik dízel-villamos hibrid üzeműre.',
        'url': '../../../../../assets/blender/mk48.obj',
        'kep': '../../../../assets/images/mk48.jpg',
    },
    {
        'id': '2',
        'nev': 'Mk-48 hibrid',
        'value': 'mk48h',
        'gyartasiev': '2010,2020',
        'ittkozlekedik': '2010 óta',
        'eredetidb':'3 db',
        'jelenlegidb': '3 db',
        'megjegyzes': '	Az Mk48 2021 mozdony az ország első hibrid kisvasúti mozdonya, kinézete különbözik a többi Mk48-as mozdonytól. A többi hibrid mozdony az eredetileg is Lillafüreden közlekedő dízel Mk48-asok átépítéséből jött létre.',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/mk48hibrid.jpg',
    },
    {
        'id': '3',
        'nev': 'C-50',
        'value': 'c50',
        'gyartasiev': '1956, 1964',
        'ittkozlekedik': '1964 óta',
        'eredetidb':'6 db',
        'jelenlegidb': '2 db',
        'megjegyzes': '-',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/c-50.jpg',
    },
    {
        'id': '4',
        'nev': '	B–26',
        'value': 'b26',
        'gyartasiev': '1952',
        'ittkozlekedik': '2006  óta',
        'eredetidb':'1 db',
        'jelenlegidb': '1 db',
        'megjegyzes': 'Típusának egyetlen megmaradt példánya',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/b26.jpg',
    },
    {
        'id': '5',
        'nev': 'Kv-4',
        'value': 'kv4',
        'gyartasiev': '1954',
        'ittkozlekedik': '1954–1972,2000–2008',
        'eredetidb':'1 db kiállítva',
        'jelenlegidb': '1 db kiállítva',
        'megjegyzes': 'Kiállítva, nem közlekedik. Beceneve: Lilla',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/kv4.jpg',
    },
    {
        'id': '6',
        'nev': 'ABamot motorvonat',
        'value': 'abamot',
        'gyartasiev': '1929',
        'ittkozlekedik': '1929–1949, 1951–1982',
        'eredetidb':'2 db',
        'jelenlegidb': '0 db',
        'megjegyzes': 'Az egyik Budapesten közlekedik, a másikat elbontották',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/abamot.jpg',
    },
    {
        'id': '7',
        'nev': '	Diamond kocsi',
        'value': 'diamond',
        'gyartasiev': '1928',
        'ittkozlekedik': '1928 óta',
        'eredetidb':'4 db',
        'jelenlegidb': '4 db',
        'megjegyzes': 'nyitott kocsi, 32 ülőhellyel',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/diamond.jpg',
    },
    {
        'id': '8',
        'nev': 'Kis MÁV kocsi',
        'value': 'kismav',
        'gyartasiev': '1928',
        'ittkozlekedik': '1928 óta',
        'eredetidb':'4 db',
        'jelenlegidb': '4 db',
        'megjegyzes': 'nyitott kocsi, 32 ülőhellyel',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/kismav.jpg',
    },
    {
        'id': '9',
        'nev': 'Nagy MÁV kocsi',
        'value': 'nagymav',
        'gyartasiev': '1979, 2021',
        'ittkozlekedik': '1979 óta',
        'eredetidb':'8 db',
        'jelenlegidb': '8 db',
        'megjegyzes': 'nyitott kocsi,44 ülőhellyel',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/nagymav.JPG',
    },
    {
        'id': '10',
        'nev': '	Bax kocsik',
        'value': 'bax',
        'gyartasiev': '1959',
        'ittkozlekedik': '1991 óta',
        'eredetidb':'4 db',
        'jelenlegidb': '4 db',
        'megjegyzes': 'Kályhafűtéses zárt kocsi 50 ülőhellyel.Hosszuk miatt csak a fővonalon közlekedhetnek',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/bax.jpg',
    },
    {
        'id': '11',
        'nev': '31-es kocsi',
        'value': '31',
        'gyartasiev': '1930-as évek; 2020, 2021',
        'ittkozlekedik': '1930-as évek óta',
        'eredetidb':'4 db',
        'jelenlegidb': '4 db',
        'megjegyzes': 'Kályhafűtéses zárt kocsi 32 db ülőhellyel',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/31.1.jpg',
    },
    {
        'id': '12',
        'nev': '	32-es kocsi',
        'value': '32',
        'gyartasiev': '1960-as évek, Akadálymentesítés: 2007',
        'ittkozlekedik': '1960-as évek óta',
        'eredetidb':'1 db',
        'jelenlegidb': '1 db',
        'megjegyzes': 'Akadálymentesített zárt kocsi 20 ülőhellyel',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/32.jpg',
    },
    {
        'id': '13',
        'nev': '33, 34-es kocsik',
        'value': '33',
        'gyartasiev': '2002',
        'ittkozlekedik': '2002 óta',
        'eredetidb':'2 db',
        'jelenlegidb': '2 db',
        'megjegyzes': 'Kályhafűtéses zárt kocsi 24 ülőhellyel',
        'url': '../../../../../assets/blender/c50.obj',
        'kep': '../../../../assets/images/33.jpg',
    },
]
